server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: zhousb-admin
  datasource:
    username: root
    password: a2080211280
    url: jdbc:mysql://59.110.166.116:3306/zhousb_db?serverTimezone=Asia/Shanghai&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: HTML
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml,classpath:mapper/*Mapper.xml
  type-aliases-package: priv.zhou.module.*.*.domain,priv.zhou.module.*.domain
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  path: logs/
#活动参数设置
app:
  enc: UTF-8
  gate: http://127.0.0.1:8080/${spring.application.name}/
  name: ${spring.application.name}
  email: false
  admin-email: flyingnoob@qq.com
  access-limit: 200




