server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    timeout: 50s
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  thymeleaf:
    mode: HTML
    cache: false
  mail:
    host: smtp.qq.com
    username: zhoutemp@qq.com
    password: zharkewamdcubjcj
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
logging:
  path: logs/
mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml,classpath:mapper/*Mapper.xml
  type-aliases-package: priv.zhou.module.*.*.domain,priv.zhou.module.*.domain
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
shiro:
  attempt-login-limit: 5 # 尝试登录最大限制
  sync-online-limit: 1 # 同时在线限制
app:
  name: ${spring.application.name}
  version: 0.1.0
  admin-email: 2080211280@qq.com
  access-limit: 200
  aes-seed: zhoudev2021
  file-service: https://zhousb.cn/file-service/
  file-upload-prefix: zhousb-admin
--- # --------------------------------------------- 开发环境 -------------------------------------------------------
spring:
  profiles: dev
  application:
    name: blog-admin
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/test_db?serverTimezone=Asia/Shanghai&useAffectedRows=true
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
app:
  enable-email: false
--- # --------------------------------------------- 正式环境 -------------------------------------------------------
spring:
  profiles: prod
  application:
    name: blog-admin
  datasource:
    username: ENC(4tON3HWNbp+2fpzDD/CJdQ==)
    password: ENC(7tU3j83fuVlwx3i3s8bxZAzAVaY39mpp)
    url: jdbc:mysql://127.0.0.1:3306/zhousb_db?serverTimezone=Asia/Shanghai&useAffectedRows=true
  redis:
    database: 0
    host: 127.0.0.1
    password: ENC(H1dbY0iQVMvilQXpfEMuoxCeWyfg7Emx)
    port: 6379
app:
  enable-email: true
  aes-seed: zhoudev2021